spring:
  profiles:
    default: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/master.xml
  mail:
    host: smtp.gmail.com
    port: 465
    username: mortalis.necrology@gmail.com
    password: sphccrbaqmplowsx
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
